# Generated by Django 3.1.1 on 2020-10-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_dream_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dreamboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('one', models.BooleanField(default=False)),
                ('two', models.BooleanField(default=False)),
                ('three', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('five', models.BooleanField(default=False)),
                ('six', models.BooleanField(default=False)),
                ('seven', models.BooleanField(default=False)),
                ('eight', models.BooleanField(default=False)),
                ('nine', models.BooleanField(default=False)),
                ('ten', models.BooleanField(default=False)),
                ('eleven', models.BooleanField(default=False)),
                ('twelve', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
