# Generated by Django 3.1.1 on 2020-10-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dreamboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreamboard',
            old_name='eight',
            new_name='atom',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='eleven',
            new_name='bird',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='five',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='four',
            new_name='cloud',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='nine',
            new_name='hand',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='one',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='seven',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='six',
            new_name='pencil',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='ten',
            new_name='skull',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='three',
            new_name='sprout',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='twelve',
            new_name='tree',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='two',
            new_name='walk',
        ),
    ]
