# Generated by Django 3.1.1 on 2020-10-16 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201016_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreamboard',
            old_name='bird',
            new_name='cloud_rain',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='cloud',
            new_name='crow',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='hand',
            new_name='hand_holding_heart',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='pencil',
            new_name='hiking',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='sprout',
            new_name='pen',
        ),
        migrations.RenameField(
            model_name='dreamboard',
            old_name='walk',
            new_name='seedling',
        ),
    ]
